version: '3.8'

services:
  nginx-reverse-proxy:
    build: nginx
    image: restful-nginx:latest
    ports:
      - 80:80
    depends_on:
      - node-express-api
      - node-hapi-api
      - java-springboot-api
      - kotlin-springboot-api
    restart: always

  node-express-api:
    build: node-express
    image: restful-node-express:latest
    restart: always

  node-hapi-api:
    build: node-hapi
    image: restful-node-hapi:latest
    restart: always

  java-springboot-api:
    build: java-springboot
    image: restful-java-springboot:latest
    restart: always

  kotlin-springboot-api:
    build: kotlin-springboot
    image: restful-kotlin-springboot:latest
    restart: always
